### ISSUE TITLE
Video preview shows a different thumbnail

### ISSUE THREAD

**Issue by Parapluie44** [MagicJinn/MrBeastify-Youtube#11]
See the following video. It'd be best to either not display anything in the preview or to ensure it's the same image as the thumbnail. Perhaps simply making it deterministic with one video = one beast?

 ![GIF](https://get.banned.today/9apcNvL.gif)

**Comment by MagicJinn** [comment]
We are attempting to fix this issue which can be seen in [this pull request](https://github.com/MagicJinn/MrBeastify-Youtube/pull/5), but we're still having trouble with Chrome (Firefox and Edge work fine). Thank you for reporting!

**Comment by MagicJinn** [comment]
The pull request was merged with main, and the issue has been fixed. We won't immediately release a new version since there's a few other issues we're working on, but it will be included in the newest future release!
