### ISSUE TITLE
firefox - non existent images also return 200

### ISSUE THREAD

**Issue by ryantanrk** [MagicJinn/MrBeastify-Youtube#18]
images that don't exist also return `200` when fetched on firefox, so the `setInterval` isn't triggered at all
firefox version 114.0.2 (latest)

![image](https://github.com/MagicJinn/MrBeastify-Youtube/assets/49902829/6c078245-f93b-4928-b080-1b0e3431e5a6)

**Comment by MagicJinn** [comment]
Should be fixed by #17
