### ISSUE TITLE
Refreshing the page without pressing F5 (clicking on the youtube logo) doesn't render new images

### ISSUE THREAD

**Issue by MagicJinn** [MagicJinn/MrBeastify-Youtube#2]
Steps to reproduce:
* Go to youtube.com -> MrBeast appears on every thumbnail
* Click on the youtube logo to refresh the homepage

Expected behaviour:
The page refreshes and MrBeast is added to every new thumbnail
Actual result:
MrBeast is not added to any new thumbnail

**Comment by ryantanrk** [comment]
check this https://github.com/ryantanrk/MrBeastify-Youtube/tree/fix-not-applying-overlay

**Comment by MagicJinn** [comment]
This does not seem to work when I test it. Could you clarify what you've changed and what it should do? I'll also update the description of the issue myself, because it probably wasn't all that clear.
