### ISSUE TITLE
Remove the money case one, as it takes up way too much of the space

### ISSUE THREAD

**Issue by Maple38** [MagicJinn/MrBeastify-Youtube#20]
I love this extension, it's very funny. But when all I can see is MrBeast, and the actual thumbnail, is entirely covered, it removes the funnys. 
![MightyBooshGIF](https://github.com/MagicJinn/MrBeastify-Youtube/assets/65621366/cc7aed5a-828e-4eff-9762-71c423b6e56d)

**Comment by MagicJinn** [comment]
Removed together with the Fake (real) MrBeast image in [this commit](https://github.com/MagicJinn/MrBeastify-Youtube/commit/d31822defb83223fbed214d149c49f5e6f99cf9e)
