### ISSUE TITLE
Random Idea: Using ML to capture sentiment from a video title and using an appropriate Mr. Beast image for funnies?

### ISSUE THREAD

**Issue by AlphaLaser** [MagicJinn/MrBeastify-Youtube#23]
Not sure how feasible this would be in terms of speed and functionality but just a random idea I had

**Comment by MagicJinn** [comment]
No need! I personally pick a MrBeast image for every thumbnail by hand. 😏
All jokes aside though, although that would be funny, I have no experience with Machine Learning, and this would most likely drastically decrease performance. I personally think the randomness of the extension is what makes it so funny xD.
