### ISSUE TITLE
Repository is unlicensed

### ISSUE THREAD

**Issue by legoandmars** [MagicJinn/MrBeastify-Youtube#24]
Hello, would you please consider adding an [open source license](https://choosealicense.com/) to this repository so people have legal permission to build/distribute/modify/etc this extension?

**Comment by MagicJinn** [comment]
Thanks for alerting me. A license has [been added](https://github.com/MagicJinn/MrBeastify-Youtube/commit/5473201fd11ccfb9b09bc66d95456ac747cd770f)
