### ISSUE TITLE
[BUG] MrBeast still shows up on shorts thumbnails in search results

### ISSUE THREAD

**Issue by Zeyu-Li** [MagicJinn/MrBeastify-Youtube#30]
Doesn't occur on home page, but does occur on the search results. I'm not sure if this can be done easily or if shorts have different metadata

browser: brave

**Comment by Zeyu-Li** [comment]
Oh I see it is worked on from https://github.com/MagicJinn/MrBeastify-Youtube/pull/22

**Comment by olivertzeng** [comment]
the scaling was incorrect but now the problem is fixed i guess

**Comment by MagicJinn** [comment]
Fixed in [the latest commit](https://github.com/MagicJinn/MrBeastify-Youtube/commit/3667e11d5f9c2c96eac5df32ca56cbd1494b3aaf). It will make it into version 1.5.
