### ISSUE TITLE
[BUG] every single picture of MrBeast showed up at once

### ISSUE THREAD

**Issue by redd-rl** [MagicJinn/MrBeastify-Youtube#35]
![image](https://github.com/MagicJinn/MrBeastify-Youtube/assets/107080537/7de0f532-25ed-45a2-ae25-ea3ad66a2850)
![image](https://github.com/MagicJinn/MrBeastify-Youtube/assets/107080537/7dcf42c0-3596-4bcf-84e3-d178c593490c)

# Steps to reproduce
????????
Have no idea.
# Expected behaviour
Not that, that's for sure.
# Actual behaviour
Every single picture of MrBeast shows up at once

**Comment by redd-rl** [comment]
![image](https://github.com/MagicJinn/MrBeastify-Youtube/assets/107080537/68ba1faf-1b50-4def-9911-9f7c550b84f9)

**Comment by ryantanrk** [comment]
it's a feature

**Comment by MagicJinn** [comment]
Yep, intended feature (1/1000 chance actually)
