### ISSUE TITLE
Can't install locally on Firefox

### ISSUE THREAD

**Issue by Blackflexxy** [MagicJinn/MrBeastify-Youtube#39]
If I download exnension from store everything works ok, but if I want to install from .zip archive Firefox says:
<img width="396" alt="image" src="https://github.com/MagicJinn/MrBeastify-Youtube/assets/68255187/9cdec711-3dfc-4c2a-96ed-90cd15ce8da3">
This is a problem, because I want to fork your repo and do the same with another streamer, also I tried it on Chrome and everything works, so it's only a Firefox problem

**Comment by JxxIT** [comment]
I think that you are importing it wrong. If I import it via about:debugging#/runtime/this-firefox, it works for me.

**Comment by MagicJinn** [comment]
Firefox doesn't allow you to import non-signed zips, except as a temporary extension. If you want to distribute it, you will have to get it signed by Mozilla. It's a bit frustrating that their error messages are so unhelpful.
