### ISSUE TITLE
Add a option to decide if you want mr beast on the left side or on the right(mirroring)

### ISSUE THREAD

**Issue by olivertzeng** [MagicJinn/MrBeastify-Youtube#45]

**Comment by MagicJinn** [comment]
If we ever add a settings menu, I'll definitely make the flip percent chance changeable. Thanks for the suggestion! There are no immediate plans for making a settings menu, but I'll leave this issue open for if I ever feel like adding it!

**Comment by olivertzeng** [comment]
> If we ever add a settings menu, I'll definitely make the flip percent chance changeable. Thanks for the suggestion! There are no immediate plans for making a settings menu, but I'll leave this issue open for if I ever feel like adding it!

Thanks!

**Comment by MagicJinn** [comment]
Flip percentage is changeable in the latest version, which will come out somewhere next week.

**Comment by olivertzeng** [comment]
> Flip percentage is changeable in the latest version, which will come out somewhere next week.

nice
