### ISSUE TITLE
Add an option to choose between different youtubers

### ISSUE THREAD

**Issue by olivertzeng** [MagicJinn/MrBeastify-Youtube#46]
There are too many YouTubers out there that are too suitable for clickbait thumbnails(for example DistroTube) So I think that you can make a preference of choosing different YouTubers and let different GitHub users commit the thumbnail database of the YouTubers they want.

**Comment by JxxIT** [comment]
Good idea! Maybe we could combine it with #44

**Comment by olivertzeng** [comment]
Cool!
This rap battle is sponsored by keeps

**Comment by MagicJinn** [comment]
I think different youtubers work best as separate extensions. There are already many alternate versions of this add-on on the chrome and firefox webstore, and I've done my best to make creating your own as easy as possible! Adding alternative youtubers to the files of this extension would cause it to surpass 100MB which is very unusual for a browser extension.

**Comment by olivertzeng** [comment]
Is there a wiki for this? @MagicJinn

**Comment by MagicJinn** [comment]
There is not currently, but I can tell you how:

1. Download the code, either by cloning the repository if you want to use version control, or just downloading it as a zip
2. Delete all images
3. Add new images. Leave no gaps in the images, so don't do 1.png, 2.png, 4.png.
4. If you don't have images with text on them, skip to step 7 and delete flip_blacklist.json
5. Add flipped images to the textFlipped folder (if you have them)
6. Edit flip_blacklist.json with the numbers of the images that should be flipped, or set `useAlternativeImages` to `false`
7. Continue to follow the steps in [this issue](https://github.com/MagicJinn/MrBeastify-Youtube/issues/16#issuecomment-1620730718)

**Comment by olivertzeng** [comment]
> There is not currently, but I can tell you how:
> 
> 1. Download the code, either by cloning the repository if you want to use version control, or just downloading it as a zip
> 2. Delete all images
> 3. Add new images. Leave no gaps in the images, so don't do 1.png, 2.png, 4.png.
> 4. If you don't have images with text on them, skip to step 7 and delete flip_blacklist.json
> 5. Add flipped images to the textFlipped folder (if you have them)
> 6. Edit flip_blacklist.json with the numbers of the images that should be flipped, or set `useAlternativeImages` to `false`
> 7. Continue to follow the steps in [this issue](https://github.com/MagicJinn/MrBeastify-Youtube/issues/16#issuecomment-1620730718)

cool
so the .pngs in step 3 are the pictures without the background, only the person & the text right?

**Comment by MagicJinn** [comment]
Yes! Only a transparent image of the youtuber

**Comment by olivertzeng** [comment]
ok but how do i remove unnessisery text on them? and how about those arrows?

**Comment by MagicJinn** [comment]
For that you'd have to use photo editing programs. Easy to use online tools include [clipdrop](clipdrop.co) and [photoroom background remover](https://www.photoroom.com/tools/background-remover).

**Comment by olivertzeng** [comment]
Cool! I'll look into that!
