### ISSUE TITLE
MrBeast showing up on chapter thumbnails (scaled incorrectly)

### ISSUE THREAD

**Issue by MeltaReal** [MagicJinn/MrBeastify-Youtube#48]
![image](https://github.com/MagicJinn/MrBeastify-Youtube/assets/115942543/e813e589-524f-40bf-92f4-afd0ea4aa4e0)
real

**Comment by MagicJinn** [comment]
Thanks for reporting. If you are using Chrome (or a Chromium browser) this is a known issue, and the fix has already been pushed, but it hasn't been approved by the chrome web store yet. If you're not using chrome, please let me know so we can get to the bottom of this!

**Comment by LorisSigrist** [comment]
I know the fix is already coming, but i still wanted to share this banger. 


<img width="990" alt="Screenshot 2023-11-13 at 14 09 30" src="https://github.com/MagicJinn/MrBeastify-Youtube/assets/43482866/7764097a-2228-41aa-9b8b-43398e133806">

Honestly this should be the default behaviour

**Comment by MagicJinn** [comment]
It's beautiful 😍

**Comment by MeltaReal** [comment]
![image](https://github.com/MagicJinn/MrBeastify-Youtube/assets/115942543/8e63249a-ea14-43e9-8851-687d7f9252e7)
his torso is the video

**Comment by MeltaReal** [comment]
Yes i am using 1.5.3
![image](https://github.com/MagicJinn/MrBeastify-Youtube/assets/115942543/8ea4bf3e-215f-4bd0-85c2-b9219d4f3a57)

**Comment by TheTechRobo** [comment]
I see it occasionally when rising the back/forward buttons in my Firefox.

**Comment by MagicJinn** [comment]
> I see it occasionally when using the back/forward buttons in my Firefox.

This seems to be the issue. I'll try to think of a fix for this.

**Comment by JxxIT** [comment]
Yeah, it is fixed on my end.

**Comment by MagicJinn** [comment]
Fixed in [1.5.4](https://github.com/MagicJinn/MrBeastify-Youtube/releases/tag/1.5.4)
