### ISSUE TITLE
Add support for Firefox on Android

### ISSUE THREAD

**Issue by mcmikecreations** [MagicJinn/MrBeastify-Youtube#49]
Android Firefox recently expanded support for extensions and I would really like to see this extension on mobile too. Would that be possible?

**Comment by MagicJinn** [comment]
I wasn't aware of any changes to the Firefox extension support for android, but the problem with developing for android is mostly that the amount of people using Youtube in their browser on mobile is minuscule. Anyone is welcome to create a port of this extension for android Firefox, but I personally won't spend any time on it.
