### ISSUE TITLE
[#future-predikshion]  wowi such innwowation!! (priority: through the roof)

### ISSUE THREAD

**Issue by ImprovedTube** [MagicJinn/MrBeastify-Youtube#52]
hi there! have not seen such dedication in implementing a feature for long!!¡¡ please consider joining us https://github.com/code-charity/youtube  

3. The day will come, that the age-average among mrbeastify's userbase passed middle school.  - Before that happens, i suggest not missing your chocolate opportunity to find a final repository (=storage facility) for whoever might overstays the joke and remains tomorrow, through placing a link to our repository - or even just including [our whole code](https://github.com/code-charity/youtube/archive/refs/heads/master.zip), for whoever feels lucky enough to click your extension icon, so that they might become seriousserious ultra alpha testers. (nothing runs by default, just a million options, toggles)

**Comment by ImprovedTube** [comment]
💗💗<code>  thanks <code> 💗<code><code>  💗<code> 💗💗💗💗💗💗💗💗💗

**Comment by ImprovedTube** [comment]
uuuhuh U too busy?? @MagicJinn     😭 i might not subscribe to your  2nd youtube channel then either 😭

**Comment by ImprovedTube** [comment]
uuuhuh U too busy?? @MagicJinn      i might not subscribe to your  2nd youtube channel then either 😭
good luck

**Comment by MagicJinn** [comment]
What on earth are you on about? I'm not really sure what you're asking of me.
