### ISSUE TITLE
Images at top of the page are not effected

### ISSUE THREAD

**Issue by MagicJinn** [MagicJinn/MrBeastify-Youtube#55]
Very inconsistent, refreshing the page leads to about a 30% chance the images are not effected

**Comment by MagicJinn** [comment]
No longer reproducable 🤔

**Comment by JxxIT** [comment]
I'm having this too

**Comment by MagicJinn** [comment]
@JxxIT when you are having this issue, could you perhaps save the entire HTML of the page? You can do this by using an extension like SingleFile ([chrome](https://chromewebstore.google.com/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle)) ([firefox](https://addons.mozilla.org/en-US/firefox/addon/single-file/)) (**preferred option**, or simply pressing `ctrl + s` and saving the entire page, then zipping the HTML and the accompanying folder, and uploading them here. Only do this when the issue occurs, and could you perhaps also send an accompanying screenshot so I can figure out which thumbnails are affected, and which are not.

**Comment by MagicJinn** [comment]
Presumed fixed until further notice

**Comment by JxxIT** [comment]
@MagicJinn Yeah sure, i'll let you know.
