### ISSUE TITLE
Accidental permissions required

### ISSUE THREAD

**Issue by luisfonsivevo** [MagicJinn/MrBeastify-Youtube#57]
I've started getting this popup to give the extension permission to do something that looks a bit shady. My quality of life has drastically decreased ever since declining the prompt, as I no longer see Mr. Breast in my YouTube thumbnails. This is a matter of life and death.
![image](https://github.com/MagicJinn/MrBeastify-Youtube/assets/19977842/2dc61b0b-6b91-45ba-a7ac-e7aab93cfb76)

**Comment by MagicJinn** [comment]
Thanks for reaching out! That is a bug. Specifically, something I forgot to remove during testing. I'll roll out an update correcting it when I can, which should hopefully reach the chrome store tomorrow.

In the meantime, enabling the permission shouldn't do anything by itself. After enabling it, you should be prompted to enable additional permissions to enable eco-mode. This is entirely optional.

If you really don't want to allow the permission, you can install the latest release version from the releases tab on Github, called Chromium.zip. You can install it if you enable developer mode.

**Comment by luisfonsivevo** [comment]
Thank you. Your efforts single-handedly keep this world spinning.

**Comment by MagicJinn** [comment]
I am just a humble man under god 🙏.

But in all seriousness the update has been submitted, should hopefully be approved soon, but it can take a few hours, sometimes up to 48 in rare cases.
